const ShoeTest = artifacts.require("ShoeTest"); // this will give us the spacebear artifacts

//describe("",()=>{}) this also works

//Truffle gives us a magic function called contract which also injects the accounts generated by the ethereum clients
contract("ShoeTest", (accounts) => {
  it("It should credit an NFT to a specific account", async () => {
    const shoeTestInstance = await ShoeTest.deployed(); // this will give us an instance
    await shoeTestInstance.safeMint(accounts[1], "FLVJ");
    const ownerOf = await shoeTestInstance.ownerOf(0);
    console.log("ownerOf(0)--->", ownerOf);
    console.log("accounts[1]-->", accounts[1]);
    expect(ownerOf).equal(accounts[1]);
  });
});
