const ShoeTest = artifacts.require("ShoeTest"); // this will give us the spacebear artifacts
const truffleAssertions = require("truffle-assertions");

//describe("",()=>{}) this also works

//Truffle gives us a magic function called contract which also injects the accounts generated by the ethereum clients
contract("ShoeTest", (accounts) => {
  it("It should credit an NFT to a specific account", async () => {
    const shoeTestInstance = await ShoeTest.deployed(); // this will give us an instance
    const txResult = await shoeTestInstance.safeMint(accounts[1], "FLVJ");
    const ownerOf = await shoeTestInstance.ownerOf(0);
    console.log("ownerOf(0)--->", ownerOf);
    console.log("accounts[1]-->", accounts[1]);
    console.log(txResult.logs[0].args);
    truffleAssertions.eventEmitted(txResult, "Transfer", {
      from: "0x0000000000000000000000000000000000000000",
      to: accounts[1],
      tokenId: web3.utils.toBN("0"),
    });
    //expect(ownerOf).equal(accounts[1]);
    //assert.equal(ownerOf, accounts[1], "Owner of Token is not equal to account 2");
  });
});
